services:
  - type: web
    name: memvault
    env: node
    buildCommand: |
      npm install --legacy-peer-deps
      npm run build
    startCommand: npx vite preview --port $PORT --host
    envVars:
      - key: NODE_VERSION
        value: 20.11.1
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
    plan: free
