services:
  - type: web
    name: memvault
    env: node
    buildCommand: |
      npm install --legacy-peer-deps
      npm run build
    startCommand: npm run preview -- --port $PORT
    envVars:
      - key: NODE_VERSION
        value: 20.11.1
      - key: PORT
        value: 10000
    plan: free
