// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gbxnhsifjvasgnnevyns.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdieG5oc2lmanZhc2dubmV2eW5zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxNDg3NDAsImV4cCI6MjA2NDcyNDc0MH0.1bKBgTnZHeAWeEOQ_i69Ui_cEWvoQvy45M3Rd-rncnQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const isProduction = process.env.NODE_ENV === 'production';
const siteUrl = isProduction ? 'https://memvault.onrender.com' : 'http://localhost:3000';

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      flowType: 'pkce',
      autoRefreshToken: true,
      detectSessionInUrl: true,
      persistSession: true,
      redirectTo: `${siteUrl}/auth/callback`,
    }
  }
);